### PR TITLE
Sphinx Doku angefangen

### PR DESCRIPTION
**Pull request by SophieAltenburg**

### CODE REVIEW

**Comment by ChristophWWagner** [comment]
Could you please provide the tikz source? I'll take care of the integration into the documentation

**Comment by ChristophWWagner** [comment]
Some build leftovers seem to have found their way into the repository. Please filter out automatically generated files in future commits (or don't add them in the first place). One good way to accomplish this is to use `git add -u` if you only have updated files. Another is populating a `.gitignore` to exclude certain files or locations from landing in the repository.

**Comment by SophieAltenburg** [comment]
I have added a text file with the TikZ source code into doc/

**Comment by ChristophWWagner** [comment]
Upon incorporation of the tikz graphic the layout broke. This is most probably due to the fixed-coordinate style without ontrol over font sizes. And maybe I also committed some human error while adjusting the coordinates to fit within the canvas (divide-by-50).

To whomever concerned: Maybe we should reduce this graphic since maintainability is really low (which to some extend stems from the high level of detail within the graphic. But what would be a kitchen without a stove? ;) ). I'd suggest switching to more intuitive graphic processors such as ditaa since it can be supported by sphinx, too.

**Pull request merged**
