### PR TITLE
Commandline Tool

### PR DESCRIPTION
**Pull request by vanrjohannes**
For further detail see Issue #3.

### CODE REVIEW

**Comment by ChristophWWagner** [comment]
I am unable to get the command-line-interface working when installing with pip. Tried on a Windows10 machine, once running IntelPython3 and once the Debian WSL of Win10:

## Windows Command Line Processor and IntelPython3
Running `python -m pip install .` within this branches' main folder installs chefkoch and puts a file named `chef` into `C:\intelpython3\Scripts\` which is what I (kind of) would expect. It is the correct python script with the shebang in the first line correctly replaced by a direct reference to the python processor as windows would expect it. The path is correctly listed inside `%PATH%`. However, windows cannot run `chef` when asked to do so.

## WSL:
When previously installed via the windows command-line-processor, the WSL subsystem sees the installation made from the IntelPython3 distribution, linking `which chef` to `/mnt/c/intelpython3/Scripts/`. It is able to run it but fails because of the windows-style shebang there.
Uninstalling chef from IntelPython3 again (see last section) the package again is installed, but this time in the WSL bash: `sudo python3 -m pip install .`. However, bash is not able to find the location of `chef`when prompted `which chef`.

## Conclusion

Something goes really bad here, but I do not know what (yet). However, I'm eager to find out.

**Comment by ChristophWWagner** [comment]
Testing it on a pure Debian9 machine making the tool available kind of works. However, `arghandler` is not registered as a requisite and must be added in setup.py. I'd suggest adding it to `installRequires`in `setup.py`

**Comment by ChristophWWagner** [comment]
Looking at the code I see the following issues:
 [ ] the nested parsers missing, that further process the remaining command line arguments within each `cmd_command` method. Please add them, parsing the remaining command line options further. Please stick to the design of PINGIT for that matter.
 [ ] when running the script somehow a version tag is misprinted on the command line.
 [ ] The doc strings should state (in the mood of an imperative) what any method does in one summary line. Further explanations can be added afterwards in a amore verbose text. See the `fastmat` or `pingit` projects for a reference on how to write such messages.

**Comment by ChristophWWagner** [comment]
> I am unable to get the command-line-interface working when installing with pip. Tried on a Windows10 machine, once running IntelPython3 and once the Debian WSL of Win10:
> 
> ## Windows Command Line Processor and IntelPython3
> Running `python -m pip install .` within this branches' main folder installs chefkoch and puts a file named `chef` into `C:\intelpython3\Scripts\` which is what I (kind of) would expect. It is the correct python script with the shebang in the first line correctly replaced by a direct reference to the python processor as windows would expect it. The path is correctly listed inside `%PATH%`. However, windows cannot run `chef` when asked to do so.
> 
> ## WSL:
> When previously installed via the windows command-line-processor, the WSL subsystem sees the installation made from the IntelPython3 distribution, linking `which chef` to `/mnt/c/intelpython3/Scripts/`. It is able to run it but fails because of the windows-style shebang there.
> Uninstalling chef from IntelPython3 again (see last section) the package again is installed, but this time in the WSL bash: `sudo python3 -m pip install .`. However, bash is not able to find the location of `chef`when prompted `which chef`.
> 
> ## Conclusion
> Something goes really bad here, but I do not know what (yet). However, I'm eager to find out.
> 
> EDIT: This seems to be an issue on windows 10 only so far when using intelpython3 and/or the WSL

Problem solved!

There is (was?) a bug (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820856) in debian that removed adding `~/.local/bin` to `$PATH` for new users. Unfortunately this thing has spread to many systems in between, amongst others many we work with on a daily basis aroung here. The best solution is to manually make sure your `$PATH` includes `~/.local/bin`. Then your favourite shell may find the pip user-installed command-line scripts.

Hooray!

**Comment by vanrjohannes** [comment]
Please rereview the merge request. Example for the usage of verbosity option in subcommands is given in 'version'. Try:
$ chef version -v

**Comment by ChristophWWagner** [comment]
Squashed some incremental commits to improve readability

**Pull request merged**
